# Generated by Django 2.0.7 on 2018-09-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(choices=[('arcade', 'arcade'), ('action', 'action'), ('racing', 'racing'), ('puzzle', 'puzzle'), ('strategy', 'strategy'), ('sports', 'sports'), ('war', 'war')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=10000)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.about')),
            ],
        ),
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.about')),
            ],
            options={
                'ordering': ('-votes',),
            },
        ),
    ]
