# Generated by Django 2.0.4 on 2018-10-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180917_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(choices=[('image/p1.jpg', 'image/p1.jpg'), ('image/p2.jpg', 'image/p2.jpg'), ('image/p3.jpg', 'image/p3.jpg'), ('image/p4.jpg', 'image/p4.jpg'), ('image/p5.jpg', 'image/p5.jpg'), ('image/p6.jpg', 'image/p6.jpg'), ('image/p7.jpg', 'image/p7.jpg'), ('image/p8.jpg', 'image/p8.jpg')], max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='launch',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.launch'),
        ),
    ]
