# Generated by Django 2.0.4 on 2018-10-17 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20181017_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.launch', unique=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.launch', unique=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.launch', unique=True),
        ),
        migrations.AlterField(
            model_name='popular',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.launch', unique=True),
        ),
    ]
