# Generated by Django 2.1.1 on 2018-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launch',
            options={'ordering': ('-year',)},
        ),
        migrations.AlterField(
            model_name='logo',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
