# Generated by Django 2.1.1 on 2018-11-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
